import type { SavedPlaceRecord } from "./savedPlaces";

export const FOOD_TRAIL_DEMO_QUERY_PARAM = "demo";

export function isFoodTrailDemoEnabled(search: string, isDev: boolean): boolean {
  if (!isDev) return false;
  const params = new URLSearchParams(search);
  return params.get(FOOD_TRAIL_DEMO_QUERY_PARAM) === "1";
}

export function createFoodTrailDemoPlaces(): SavedPlaceRecord[] {
  return [
    {
      id: "demo-breakfast-cafe-1",
      placeId: "demo-breakfast-cafe-1",
      title: "Brahmin Brew Cafe",
      category: "Taste",
      distanceKm: 0.9,
      metaPrimary: "Breakfast cafe",
      metaSecondary: "Filter coffee, idli, dosa",
      locality: "Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "12th Main, Indiranagar, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Cafe", "Breakfast", "Coffee"],
      createdAtMs: 1,
    },
    {
      id: "demo-meal-1",
      placeId: "demo-meal-1",
      title: "Meghana Biryani Kitchen",
      category: "Taste",
      distanceKm: 2.6,
      metaPrimary: "Dinner",
      metaSecondary: "Biryani, kebab, family meal",
      locality: "Koramangala",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "5th Block, Koramangala, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Biryani", "Dinner", "Meal"],
      createdAtMs: 2,
    },
    {
      id: "demo-meal-2",
      placeId: "demo-meal-2",
      title: "Karavalli Dinner House",
      category: "Taste",
      distanceKm: 2.1,
      metaPrimary: "Dinner",
      metaSecondary: "Seafood dinner, curry, family restaurant",
      locality: "Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "CMH Road, Indiranagar, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Dinner", "Restaurant", "Seafood"],
      createdAtMs: 21,
    },
    {
      id: "demo-dessert-1",
      placeId: "demo-dessert-1",
      title: "Milkyway Gelato Bar",
      category: "Taste",
      distanceKm: 1.4,
      metaPrimary: "Dessert",
      metaSecondary: "Gelato, waffle, brownie",
      locality: "Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "100 Feet Road, Indiranagar, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Dessert", "Gelato", "Waffle"],
      createdAtMs: 3,
    },
    {
      id: "demo-dessert-2",
      placeId: "demo-dessert-2",
      title: "Lavonne Pastry Lab",
      category: "Taste",
      distanceKm: 1.2,
      metaPrimary: "Dessert",
      metaSecondary: "Pastry, cake, brownie",
      locality: "Koramangala",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "8th Block, Koramangala, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Dessert", "Pastry", "Cake"],
      createdAtMs: 31,
    },
    {
      id: "demo-snack-1",
      placeId: "demo-snack-1",
      title: "VV Puram Chaat Corner",
      category: "Taste",
      distanceKm: 3.1,
      metaPrimary: "Snack",
      metaSecondary: "Street food, chaat, quick bites",
      locality: "Basavanagudi",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "Food Street, Basavanagudi, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Snack", "Street Food", "Chaat"],
      createdAtMs: 4,
    },
    {
      id: "demo-cafe-2",
      placeId: "demo-cafe-2",
      title: "Roastery Corner",
      category: "Taste",
      distanceKm: 1.8,
      metaPrimary: "Cafe",
      metaSecondary: "Coffee, pastry, brunch",
      locality: "Koramangala",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "80 Feet Road, Koramangala, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Cafe", "Brunch", "Pastry"],
      createdAtMs: 5,
    },
    {
      id: "demo-cafe-3",
      placeId: "demo-cafe-3",
      title: "Third Wave Espresso Room",
      category: "Taste",
      distanceKm: 1.1,
      metaPrimary: "Cafe",
      metaSecondary: "Espresso, croissant, coffee",
      locality: "Indiranagar",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      fullAddress: "100 Feet Road, Indiranagar, Bengaluru",
      videoUrl: "",
      imageUrl: "",
      tags: ["Cafe", "Coffee", "Espresso"],
      createdAtMs: 51,
    },
  ];
}
