import type { SavedPlaceRecord } from "./savedPlaces";

export const WEEKEND_PLANNER_DEMO_QUERY_PARAM = "demo";

export function isWeekendPlannerDemoEnabled(search: string, isDev: boolean): boolean {
  if (!isDev) return false;
  const params = new URLSearchParams(search);
  return params.get(WEEKEND_PLANNER_DEMO_QUERY_PARAM) === "1";
}

export function createWeekendPlannerDemoPlaces(): SavedPlaceRecord[] {
  return [
    {
      id: "weekend-demo-taste-1",
      placeId: "weekend-demo-taste-1",
      title: "Basanti Breakfast Club",
      category: "Taste",
      distanceKm: 1.1,
      metaPrimary: "Breakfast cafe",
      metaSecondary: "Poha, chai, light breakfast",
      locality: "Boring Road",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Boring Road, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Breakfast", "Cafe", "Tea"],
      createdAtMs: 1,
    },
    {
      id: "weekend-demo-taste-2",
      placeId: "weekend-demo-taste-2",
      title: "Patliputra Biryani House",
      category: "Taste",
      distanceKm: 2.9,
      metaPrimary: "Meal",
      metaSecondary: "Biryani, kebab, dinner plates",
      locality: "Patliputra Colony",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Patliputra Colony, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Biryani", "Meal", "Dinner"],
      createdAtMs: 2,
    },
    {
      id: "weekend-demo-taste-3",
      placeId: "weekend-demo-taste-3",
      title: "Kulfi Ghar",
      category: "Taste",
      distanceKm: 2.2,
      metaPrimary: "Dessert",
      metaSecondary: "Kulfi, falooda, sweet break",
      locality: "Fraser Road",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Fraser Road, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Dessert", "Kulfi", "Sweet"],
      createdAtMs: 3,
    },
    {
      id: "weekend-demo-explore-1",
      placeId: "weekend-demo-explore-1",
      title: "Bihar Museum",
      category: "Explore",
      distanceKm: 1.8,
      metaPrimary: "Museum",
      metaSecondary: "Art galleries, city history",
      locality: "Bailey Road",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Bailey Road, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Museum", "History", "Explore"],
      createdAtMs: 4,
    },
    {
      id: "weekend-demo-explore-2",
      placeId: "weekend-demo-explore-2",
      title: "Golghar Viewpoint",
      category: "Explore",
      distanceKm: 2.5,
      metaPrimary: "Landmark",
      metaSecondary: "River views, city landmark",
      locality: "Gandhi Maidan",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Gandhi Maidan, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Landmark", "Viewpoint", "Walk"],
      createdAtMs: 5,
    },
    {
      id: "weekend-demo-activity-1",
      placeId: "weekend-demo-activity-1",
      title: "Ganges Riverside Kayak Club",
      category: "Activity",
      distanceKm: 3.3,
      metaPrimary: "Outdoor activity",
      metaSecondary: "Kayak session, sunset slot",
      locality: "Collectorate Ghat",
      city: "Patna",
      state: "Bihar",
      country: "India",
      fullAddress: "Collectorate Ghat, Patna",
      videoUrl: "",
      imageUrl: "",
      tags: ["Kayak", "Outdoor", "Activity"],
      createdAtMs: 6,
    },
  ];
}
